# HYDRA / Hydrasales - InstanceName must match this SQL host (@@SERVERNAME).
$CustomerCode = 'HYDRA'
$DisplayName = 'Hydrasales'
$InstanceName = 'HYDRASRV'
$LocalSqlUser = 'rpmassure'
$LocalSqlPassword = '@ssuR3me!'
$CentralSqlUser = 'rpmassure'
$CentralSqlPassword = '@ssuR3me!'
$CentralDataSource = '102.222.21.220,14333'
$CentralDatabase = 'RPMAssure_App'
$CollectDir = 'C:\RPM-Assure\Sql\customers\HYDRA'
$LogDir = 'C:\RPM-Assure\Sql\customers\HYDRA\logs'
