param(
  [string]$InstallDir = 'C:\Program Files\RPM Resources\RPM Assure',
  [string]$SqlServer = '',
  [string]$SqlDatabase = 'RPMAssure_App',
  [string]$SqlUser = '',
  [string]$SqlPassword = '',
  [string]$SqlTrustCert = 'true',
  [string]$AppUrl = 'https://assure.rpmresources.co.za'
)
$ErrorActionPreference = 'Stop'
$configDir = Join-Path $env:ProgramData 'RPM Resources\RPM Assure\config'
New-Item -ItemType Directory -Force -Path $configDir | Out-Null
$envPath = Join-Path $configDir 'app.env'

# Preserve existing secret if present
$existingSecret = ''
if (Test-Path $envPath) {
  Get-Content $envPath | ForEach-Object {
    if ($_ -match '^\s*BETTER_AUTH_SECRET\s*=\s*(.+)$') { $existingSecret = $Matches[1].Trim() }
  }
}
if (-not $existingSecret) {
  $bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  $existingSecret = ([BitConverter]::ToString($bytes) -replace '-','').ToLowerInvariant()
}

if (-not $SqlServer) { throw 'SQLSERVER property is required for silent config' }

$lines = @(
  '# Generated by RPM Assure installer',
  "RPM_ASSURE_DATA_MODE=auto",
  "RPM_ASSURE_SQL_SERVER=$SqlServer",
  "RPM_ASSURE_SQL_DATABASE=$SqlDatabase",
  "RPM_ASSURE_SQL_USER=$SqlUser",
  "RPM_ASSURE_SQL_PASSWORD=$SqlPassword",
  "RPM_ASSURE_SQL_TRUST_CERT=$SqlTrustCert",
  "VITE_AUTH_ENABLED=true",
  "BETTER_AUTH_URL=$AppUrl",
  "BETTER_AUTH_TRUSTED_ORIGINS=$AppUrl",
  "BETTER_AUTH_SECRET=$existingSecret",
  "PORT=8081",
  "NITRO_PORT=8081",
  "HOST=0.0.0.0"
)
$utf8 = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllLines($envPath, $lines, $utf8)

# Mirror into app folder for node process
$appEnv = Join-Path $InstallDir 'app\.env.local'
$appDir = Split-Path $appEnv
if (Test-Path $appDir) {
  [IO.File]::WriteAllLines($appEnv, $lines, $utf8)
}
Write-Host "Wrote $envPath"
