# Able Tracers - RMM / Cove / EPP host agent. No SYSPRO cover.
$CustomerCode = 'ABLE'
$DisplayName = 'Able Tracers'
$InstanceName = ''
$SqlInstanceName = ''
$LocalSqlUser = 'rpmassure'
$LocalSqlPassword = ''
$CentralDataSource = '102.222.21.220,14333'
$CentralDatabase = 'RPMAssure_App'
$CentralSqlUser = 'rpmassure'
$CentralSqlPassword = ''
