# Install ONE Windows task: all API pulls every 15 minutes.
# Pulseway + Cove + Bitdefender + CSP Graph (soft-fail each).
# Run as Administrator on the APP / central host.
# Pure ASCII.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File "$env:USERPROFILE\Downloads\Install-All-Api-Collect-15min.ps1"
#
# Optional:
#   -Minutes 15
#   -SkipCsp                 # do not call Graph on this interval
#   -KeepOldTasks            # leave Pulseway/Cove/Exco tasks alone (default: disable them)
#   -RunNow

param(
  [string]$Root = "C:\RPM-Assure",
  [int]$Minutes = 15,
  [switch]$SkipCsp,
  [switch]$KeepOldTasks,
  [switch]$RunNow
)

$ErrorActionPreference = "Stop"
if ($Minutes -lt 10) { $Minutes = 10 }
if ($Minutes -gt 60) { $Minutes = 60 }

$ops = Join-Path $Root "Sql\ops"
$logDir = Join-Path $ops "logs"
New-Item -ItemType Directory -Force -Path $ops, $logDir | Out-Null

$runner = Join-Path $ops "Run-All-Api-Collects-Scheduled.ps1"
$taskName = "RPMAssure-All-Api-Collect"

# --- Write scheduled runner (soft-fail each leg) ---
$skipCspLine = if ($SkipCsp) { '$SkipCsp = $true' } else { '$SkipCsp = $false' }

$runnerBody = @"
# Auto-generated by Install-All-Api-Collect-15min.ps1
# Sequential API collect. Soft-fail each leg. Pure ASCII.
param([string]`$Root = "C:\RPM-Assure")
`$ErrorActionPreference = "Continue"
$skipCspLine
`$logDir = Join-Path `$Root "Sql\ops\logs"
New-Item -ItemType Directory -Force -Path `$logDir | Out-Null
`$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
`$log = Join-Path `$logDir ("sched_all_api_" + `$stamp + ".log")
function W([string]`$m) {
  `$line = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss") + "Z " + `$m
  Add-Content -LiteralPath `$log -Value `$line -ErrorAction SilentlyContinue
  Write-Host `$line
}
function Run-Leg([string]`$Name, [string]`$Path, [string[]]`$Extra = @()) {
  if (-not (Test-Path -LiteralPath `$Path)) {
    W ("SKIP " + `$Name + " missing " + `$Path)
    return
  }
  W ("=== RUN " + `$Name + " ===")
  `$sw = [Diagnostics.Stopwatch]::StartNew()
  try {
    `$args = @("-NoProfile","-ExecutionPolicy","Bypass","-File",`$Path) + `$Extra
    `$p = Start-Process -FilePath "powershell.exe" -ArgumentList `$args -Wait -PassThru -NoNewWindow `
      -RedirectStandardOutput (Join-Path `$logDir ("sched_" + `$Name + "_" + `$stamp + "_out.txt")) `
      -RedirectStandardError  (Join-Path `$logDir ("sched_" + `$Name + "_" + `$stamp + "_err.txt"))
    W ("DONE " + `$Name + " exit=" + `$p.ExitCode + " sec=" + [int]`$sw.Elapsed.TotalSeconds)
  } catch {
    W ("FAIL " + `$Name + " " + `$_.Exception.Message)
  }
  `$outF = Join-Path `$logDir ("sched_" + `$Name + "_" + `$stamp + "_out.txt")
  if (Test-Path `$outF) {
    Get-Content `$outF -Tail 15 -EA SilentlyContinue | ForEach-Object { W ("  | " + `$_) }
  }
}
W "=== All API collect schedule start ==="
Run-Leg "Pulseway" (Join-Path `$Root "Sql\rmm\pulseway\Collect-Pulseway-To-RPMAssure.ps1")
Run-Leg "Cove" (Join-Path `$Root "Sql\cove\Collect-Cove-To-RPMAssure.ps1")
Run-Leg "Bitdefender" (Join-Path `$Root "Sql\bitdefender\Collect-Bitdefender-To-RPMAssure.ps1")
if (-not `$SkipCsp) {
  Run-Leg "CspGraph" (Join-Path `$Root "Sql\csp\Collect-Csp-Graph-To-RPMAssure.ps1") @("-WindowsAuth","-SkipSchema")
} else {
  W "SKIP CspGraph (SkipCsp)"
}
W ("=== All API collect done log=" + `$log)
"@

[IO.File]::WriteAllText($runner, $runnerBody, [Text.UTF8Encoding]::new($false))
Write-Host "Wrote $runner" -ForegroundColor Green

# --- ACL so SYSTEM can run ---
try {
  icacls $ops /grant "SYSTEM:(OI)(CI)(RX)" "Administrators:(OI)(CI)(F)" 2>$null | Out-Null
  icacls $Root /grant "SYSTEM:(OI)(CI)(RX)" 2>$null | Out-Null
} catch {}

# --- Disable overlapping API tasks (avoid double pulls) ---
$oldTasks = @(
  "RPMAssure-Pulseway-Collect",
  "RPMAssure-Cove-CyberBackup",
  "RPMAssure-Exco-Data-Refresh"
)
if (-not $KeepOldTasks) {
  foreach ($t in $oldTasks) {
    try {
      $st = Get-ScheduledTask -TaskName $t -ErrorAction SilentlyContinue
      if ($st) {
        Disable-ScheduledTask -TaskName $t -ErrorAction SilentlyContinue | Out-Null
        Write-Host "Disabled overlapping task: $t" -ForegroundColor Yellow
      }
    } catch {}
  }
  Write-Host "Note: RPMAssure-Csp-GraphCollect (daily) left as-is. CSP also runs in the 15-min task unless -SkipCsp." -ForegroundColor Cyan
}

# --- Create / replace main task ---
$tr = 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "' + $runner + '" -Root "' + $Root + '"'

Write-Host ("Creating task $taskName every $Minutes min ...") -ForegroundColor Cyan
cmd.exe /c ("schtasks /Delete /TN `"" + $taskName + "`" /F >nul 2>&1") | Out-Null
$create = 'schtasks /Create /F /TN "' + $taskName + '" /TR "' + $tr + '" /SC MINUTE /MO ' + $Minutes + ' /RU SYSTEM /RL HIGHEST'
cmd.exe /c $create
if ($LASTEXITCODE -ne 0) {
  throw "schtasks create failed exit=$LASTEXITCODE - run as Administrator"
}

Write-Host ""
Write-Host "=== INSTALLED ===" -ForegroundColor Green
Write-Host ("  Task:     " + $taskName)
Write-Host ("  Interval: every " + $Minutes + " minutes")
Write-Host ("  Runner:   " + $runner)
Write-Host ("  Logs:     " + $logDir + "\sched_all_api_*.log")
Write-Host ("  CSP:      " + $(if ($SkipCsp) { "skipped" } else { "included each cycle" }))
Write-Host ""

try {
  Get-ScheduledTask -TaskName $taskName | Format-Table TaskName, State -AutoSize
  Get-ScheduledTaskInfo -TaskName $taskName | Format-List LastRunTime, LastTaskResult, NextRunTime
} catch {
  schtasks /Query /TN $taskName /FO LIST /V | Select-String "TaskName|Status|Next Run|Last Run|Task To Run"
}

if ($RunNow) {
  Write-Host "Starting once now..." -ForegroundColor Cyan
  Start-ScheduledTask -TaskName $taskName
  Start-Sleep -Seconds 2
  Get-ScheduledTask -TaskName $taskName | Format-Table TaskName, State -AutoSize
}

Write-Host ""
Write-Host "Manual run:" -ForegroundColor Cyan
Write-Host ('  Start-ScheduledTask -TaskName "' + $taskName + '"')
Write-Host ('  powershell -NoProfile -ExecutionPolicy Bypass -File "' + $runner + '"')
Write-Host "=== Done ===" -ForegroundColor Green
