/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetPackRouteImport } from './routes/get-pack'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackRouteImport } from './routes/pack'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as UiLabRouteImport } from './routes/ui-lab'
import { Route as ApiBootstrapAdminRouteImport } from './routes/api/bootstrap-admin'
import { Route as ApiIopsRouteImport } from './routes/api/iops'
import { Route as ApiPatchesRouteImport } from './routes/api/patches'
import { Route as ApiPortfolioRefreshRouteImport } from './routes/api/portfolio-refresh'
import { Route as ApiReportPreviewRouteImport } from './routes/api/report-preview'
import { Route as CustomersCodeRouteImport } from './routes/customers.$code'
import { Route as DownloadsSplatRouteImport } from './routes/downloads.$'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'
import { Route as SettingsAlertsRouteImport } from './routes/settings.alerts'
import { Route as SettingsAuditRouteImport } from './routes/settings.audit'
import { Route as SettingsChromeRouteImport } from './routes/settings.chrome'
import { Route as SettingsCollectRouteImport } from './routes/settings.collect'
import { Route as SettingsDashboardRouteImport } from './routes/settings.dashboard'
import { Route as SettingsInfrastructureRouteImport } from './routes/settings.infrastructure'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsLabelsRouteImport } from './routes/settings.labels'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsQueryRouteImport } from './routes/settings.query'
import { Route as SettingsRagRouteImport } from './routes/settings.rag'
import { Route as SettingsReportsRouteImport } from './routes/settings.reports'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsSmtpRouteImport } from './routes/settings.smtp'
import { Route as SettingsSqlRouteImport } from './routes/settings.sql'
import { Route as SettingsSslRouteImport } from './routes/settings.ssl'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as ApiAgentPackCodeRouteImport } from './routes/api/agent-pack.$code'
import { Route as ApiAgentHeartbeatRouteImport } from './routes/api/agent/heartbeat'
import { Route as ApiAgentOnboardRouteImport } from './routes/api/agent/onboard'
import { Route as ApiAgentPackRouteImport } from './routes/api/agent/pack'
import { Route as ApiAgentSyncRouteImport } from './routes/api/agent/sync'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronWeeklyReportRouteImport } from './routes/api/cron/weekly-report'
import { Route as ApiPulsewayWebhookRouteImport } from './routes/api/pulseway.webhook'
import { Route as ApiWpEstateRouteImport } from './routes/api/wp.estate'
import { Route as CustomersCodeIndexRouteImport } from './routes/customers.$code.index'
import { Route as CustomersCodeAmsRouteImport } from './routes/customers.$code.ams'
import { Route as CustomersCodeCoveRouteImport } from './routes/customers.$code.cove'
import { Route as CustomersCodeCspRouteImport } from './routes/customers.$code.csp'
import { Route as CustomersCodeEppRouteImport } from './routes/customers.$code.epp'
import { Route as CustomersCodeRmmRouteImport } from './routes/customers.$code.rmm'
import { Route as CustomersCodeSysproRouteImport } from './routes/customers.$code.syspro'
import { Route as CustomersCodeTicketsRouteImport } from './routes/customers.$code.tickets'
import { Route as CustomersCodeAmsIndexRouteImport } from './routes/customers.$code.ams.index'
import { Route as CustomersCodeAmsChangeRouteImport } from './routes/customers.$code.ams.change'
import { Route as CustomersCodeAmsIncidentsRouteImport } from './routes/customers.$code.ams.incidents'
import { Route as CustomersCodeAmsRisksRouteImport } from './routes/customers.$code.ams.risks'
import { Route as CustomersCodeAmsSlaRouteImport } from './routes/customers.$code.ams.sla'
import { Route as CustomersCodeCoveIndexRouteImport } from './routes/customers.$code.cove.index'
import { Route as CustomersCodeCoveDevicesRouteImport } from './routes/customers.$code.cove.devices'
import { Route as CustomersCodeCoveMappingRouteImport } from './routes/customers.$code.cove.mapping'
import { Route as CustomersCodeCoveOverviewRouteImport } from './routes/customers.$code.cove.overview'
import { Route as CustomersCodeCoveRecoveryRouteImport } from './routes/customers.$code.cove.recovery'
import { Route as CustomersCodeCoveRetentionRouteImport } from './routes/customers.$code.cove.retention'
import { Route as CustomersCodeCoveSlaRouteImport } from './routes/customers.$code.cove.sla'
import { Route as CustomersCodeCspIndexRouteImport } from './routes/customers.$code.csp.index'
import { Route as CustomersCodeCspGlobalAdminsRouteImport } from './routes/customers.$code.csp.global-admins'
import { Route as CustomersCodeCspLicensesRouteImport } from './routes/customers.$code.csp.licenses'
import { Route as CustomersCodeCspMfaRouteImport } from './routes/customers.$code.csp.mfa'
import { Route as CustomersCodeCspSecureScoreRouteImport } from './routes/customers.$code.csp.secure-score'
import { Route as CustomersCodeCspUsersRouteImport } from './routes/customers.$code.csp.users'
import { Route as CustomersCodeEppIndexRouteImport } from './routes/customers.$code.epp.index'
import { Route as CustomersCodeEppEndpointsRouteImport } from './routes/customers.$code.epp.endpoints'
import { Route as CustomersCodeEppIncidentsRouteImport } from './routes/customers.$code.epp.incidents'
import { Route as CustomersCodeEppModulesRouteImport } from './routes/customers.$code.epp.modules'
import { Route as CustomersCodeEppQuarantineRouteImport } from './routes/customers.$code.epp.quarantine'
import { Route as CustomersCodeEppSlaRouteImport } from './routes/customers.$code.epp.sla'
import { Route as CustomersCodeRmmIndexRouteImport } from './routes/customers.$code.rmm.index'
import { Route as CustomersCodeRmmAlertsRouteImport } from './routes/customers.$code.rmm.alerts'
import { Route as CustomersCodeRmmDevicesRouteImport } from './routes/customers.$code.rmm.devices'
import { Route as CustomersCodeRmmEventsRouteImport } from './routes/customers.$code.rmm.events'
import { Route as CustomersCodeRmmIopsRouteImport } from './routes/customers.$code.rmm.iops'
import { Route as CustomersCodeRmmMappingRouteImport } from './routes/customers.$code.rmm.mapping'
import { Route as CustomersCodeRmmOverviewRouteImport } from './routes/customers.$code.rmm.overview'
import { Route as CustomersCodeRmmPatchRouteImport } from './routes/customers.$code.rmm.patch'
import { Route as CustomersCodeRmmSlaRouteImport } from './routes/customers.$code.rmm.sla'
import { Route as CustomersCodeRmmWorkstationsRouteImport } from './routes/customers.$code.rmm.workstations'
import { Route as CustomersCodeSysproIndexRouteImport } from './routes/customers.$code.syspro.index'
import { Route as CustomersCodeSysproDayEndRouteImport } from './routes/customers.$code.syspro.day-end'
import { Route as CustomersCodeSysproDtrRouteImport } from './routes/customers.$code.syspro.dtr'
import { Route as CustomersCodeSysproHealthRouteImport } from './routes/customers.$code.syspro.health'
import { Route as CustomersCodeSysproHotfixesRouteImport } from './routes/customers.$code.syspro.hotfixes'
import { Route as CustomersCodeSysproJobsRouteImport } from './routes/customers.$code.syspro.jobs'
import { Route as CustomersCodeSysproLicenseRouteImport } from './routes/customers.$code.syspro.license'
import { Route as CustomersCodeSysproOperatorsRouteImport } from './routes/customers.$code.syspro.operators'
import { Route as CustomersCodeSysproSecurityRouteImport } from './routes/customers.$code.syspro.security'
import { Route as CustomersCodeSysproSlaRouteImport } from './routes/customers.$code.syspro.sla'
import { Route as CustomersCodeSysproSqlRouteImport } from './routes/customers.$code.syspro.sql'
import { Route as CustomersCodeTicketsIndexRouteImport } from './routes/customers.$code.tickets.index'
import { Route as CustomersCodeTicketsClosedRouteImport } from './routes/customers.$code.tickets.closed'
import { Route as CustomersCodeTicketsOpenRouteImport } from './routes/customers.$code.tickets.open'
import { Route as CustomersCodeTicketsResolvedRouteImport } from './routes/customers.$code.tickets.resolved'
import { Route as CustomersCodeTicketsSlaRouteImport } from './routes/customers.$code.tickets.sla'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetPackRoute = GetPackRouteImport.update({
  id: '/get-pack',
  path: '/get-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const UiLabRoute = UiLabRouteImport.update({
  id: '/ui-lab',
  path: '/ui-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapAdminRoute = ApiBootstrapAdminRouteImport.update({
  id: '/api/bootstrap-admin',
  path: '/api/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIopsRoute = ApiIopsRouteImport.update({
  id: '/api/iops',
  path: '/api/iops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatchesRoute = ApiPatchesRouteImport.update({
  id: '/api/patches',
  path: '/api/patches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioRefreshRoute = ApiPortfolioRefreshRouteImport.update({
  id: '/api/portfolio-refresh',
  path: '/api/portfolio-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportPreviewRoute = ApiReportPreviewRouteImport.update({
  id: '/api/report-preview',
  path: '/api/report-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCodeRoute = CustomersCodeRouteImport.update({
  id: '/customers/$code',
  path: '/customers/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsSplatRoute = DownloadsSplatRouteImport.update({
  id: '/downloads/$',
  path: '/downloads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAlertsRoute = SettingsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChromeRoute = SettingsChromeRouteImport.update({
  id: '/chrome',
  path: '/chrome',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCollectRoute = SettingsCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDashboardRoute = SettingsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInfrastructureRoute = SettingsInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLabelsRoute = SettingsLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsQueryRoute = SettingsQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRagRoute = SettingsRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsReportsRoute = SettingsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSmtpRoute = SettingsSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSqlRoute = SettingsSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSslRoute = SettingsSslRouteImport.update({
  id: '/ssl',
  path: '/ssl',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAgentPackCodeRoute = ApiAgentPackCodeRouteImport.update({
  id: '/api/agent-pack/$code',
  path: '/api/agent-pack/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentHeartbeatRoute = ApiAgentHeartbeatRouteImport.update({
  id: '/api/agent/heartbeat',
  path: '/api/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentOnboardRoute = ApiAgentOnboardRouteImport.update({
  id: '/api/agent/onboard',
  path: '/api/agent/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPackRoute = ApiAgentPackRouteImport.update({
  id: '/api/agent/pack',
  path: '/api/agent/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSyncRoute = ApiAgentSyncRouteImport.update({
  id: '/api/agent/sync',
  path: '/api/agent/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWeeklyReportRoute = ApiCronWeeklyReportRouteImport.update({
  id: '/api/cron/weekly-report',
  path: '/api/cron/weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulsewayWebhookRoute = ApiPulsewayWebhookRouteImport.update({
  id: '/api/pulseway/webhook',
  path: '/api/pulseway/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWpEstateRoute = ApiWpEstateRouteImport.update({
  id: '/api/wp/estate',
  path: '/api/wp/estate',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCodeIndexRoute = CustomersCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeAmsRoute = CustomersCodeAmsRouteImport.update({
  id: '/ams',
  path: '/ams',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeCoveRoute = CustomersCodeCoveRouteImport.update({
  id: '/cove',
  path: '/cove',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeCspRoute = CustomersCodeCspRouteImport.update({
  id: '/csp',
  path: '/csp',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeEppRoute = CustomersCodeEppRouteImport.update({
  id: '/epp',
  path: '/epp',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeRmmRoute = CustomersCodeRmmRouteImport.update({
  id: '/rmm',
  path: '/rmm',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeSysproRoute = CustomersCodeSysproRouteImport.update({
  id: '/syspro',
  path: '/syspro',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeTicketsRoute = CustomersCodeTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => CustomersCodeRoute,
} as any)
const CustomersCodeAmsIndexRoute = CustomersCodeAmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersCodeAmsRoute,
} as any)
const CustomersCodeAmsChangeRoute = CustomersCodeAmsChangeRouteImport.update({
  id: '/change',
  path: '/change',
  getParentRoute: () => CustomersCodeAmsRoute,
} as any)
const CustomersCodeAmsIncidentsRoute =
  CustomersCodeAmsIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => CustomersCodeAmsRoute,
  } as any)
const CustomersCodeAmsRisksRoute = CustomersCodeAmsRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => CustomersCodeAmsRoute,
} as any)
const CustomersCodeAmsSlaRoute = CustomersCodeAmsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => CustomersCodeAmsRoute,
} as any)
const CustomersCodeCoveIndexRoute = CustomersCodeCoveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersCodeCoveRoute,
} as any)
const CustomersCodeCoveDevicesRoute =
  CustomersCodeCoveDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => CustomersCodeCoveRoute,
  } as any)
const CustomersCodeCoveMappingRoute =
  CustomersCodeCoveMappingRouteImport.update({
    id: '/mapping',
    path: '/mapping',
    getParentRoute: () => CustomersCodeCoveRoute,
  } as any)
const CustomersCodeCoveOverviewRoute =
  CustomersCodeCoveOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => CustomersCodeCoveRoute,
  } as any)
const CustomersCodeCoveRecoveryRoute =
  CustomersCodeCoveRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => CustomersCodeCoveRoute,
  } as any)
const CustomersCodeCoveRetentionRoute =
  CustomersCodeCoveRetentionRouteImport.update({
    id: '/retention',
    path: '/retention',
    getParentRoute: () => CustomersCodeCoveRoute,
  } as any)
const CustomersCodeCoveSlaRoute = CustomersCodeCoveSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => CustomersCodeCoveRoute,
} as any)
const CustomersCodeCspIndexRoute = CustomersCodeCspIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersCodeCspRoute,
} as any)
const CustomersCodeCspGlobalAdminsRoute =
  CustomersCodeCspGlobalAdminsRouteImport.update({
    id: '/global-admins',
    path: '/global-admins',
    getParentRoute: () => CustomersCodeCspRoute,
  } as any)
const CustomersCodeCspLicensesRoute =
  CustomersCodeCspLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => CustomersCodeCspRoute,
  } as any)
const CustomersCodeCspMfaRoute = CustomersCodeCspMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => CustomersCodeCspRoute,
} as any)
const CustomersCodeCspSecureScoreRoute =
  CustomersCodeCspSecureScoreRouteImport.update({
    id: '/secure-score',
    path: '/secure-score',
    getParentRoute: () => CustomersCodeCspRoute,
  } as any)
const CustomersCodeCspUsersRoute = CustomersCodeCspUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CustomersCodeCspRoute,
} as any)
const CustomersCodeEppIndexRoute = CustomersCodeEppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersCodeEppRoute,
} as any)
const CustomersCodeEppEndpointsRoute =
  CustomersCodeEppEndpointsRouteImport.update({
    id: '/endpoints',
    path: '/endpoints',
    getParentRoute: () => CustomersCodeEppRoute,
  } as any)
const CustomersCodeEppIncidentsRoute =
  CustomersCodeEppIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => CustomersCodeEppRoute,
  } as any)
const CustomersCodeEppModulesRoute = CustomersCodeEppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => CustomersCodeEppRoute,
} as any)
const CustomersCodeEppQuarantineRoute =
  CustomersCodeEppQuarantineRouteImport.update({
    id: '/quarantine',
    path: '/quarantine',
    getParentRoute: () => CustomersCodeEppRoute,
  } as any)
const CustomersCodeEppSlaRoute = CustomersCodeEppSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => CustomersCodeEppRoute,
} as any)
const CustomersCodeRmmIndexRoute = CustomersCodeRmmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmAlertsRoute = CustomersCodeRmmAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmDevicesRoute = CustomersCodeRmmDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmEventsRoute = CustomersCodeRmmEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmIopsRoute = CustomersCodeRmmIopsRouteImport.update({
  id: '/iops',
  path: '/iops',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmMappingRoute = CustomersCodeRmmMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmOverviewRoute =
  CustomersCodeRmmOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => CustomersCodeRmmRoute,
  } as any)
const CustomersCodeRmmPatchRoute = CustomersCodeRmmPatchRouteImport.update({
  id: '/patch',
  path: '/patch',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmSlaRoute = CustomersCodeRmmSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => CustomersCodeRmmRoute,
} as any)
const CustomersCodeRmmWorkstationsRoute =
  CustomersCodeRmmWorkstationsRouteImport.update({
    id: '/workstations',
    path: '/workstations',
    getParentRoute: () => CustomersCodeRmmRoute,
  } as any)
const CustomersCodeSysproIndexRoute =
  CustomersCodeSysproIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CustomersCodeSysproRoute,
  } as any)
const CustomersCodeSysproDayEndRoute =
  CustomersCodeSysproDayEndRouteImport.update({
    id: '/day-end',
    path: '/day-end',
    getParentRoute: () => CustomersCodeSysproRoute,
  } as any)
const CustomersCodeSysproDtrRoute = CustomersCodeSysproDtrRouteImport.update({
  id: '/dtr',
  path: '/dtr',
  getParentRoute: () => CustomersCodeSysproRoute,
} as any)
const CustomersCodeSysproHealthRoute =
  CustomersCodeSysproHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => CustomersCodeSysproRoute,
  } as any)
const CustomersCodeSysproHotfixesRoute =
  CustomersCodeSysproHotfixesRouteImport.update({
    id: '/hotfixes',
    path: '/hotfixes',
    getParentRoute: () => CustomersCodeSysproRoute,
  } as any)
const CustomersCodeSysproJobsRoute = CustomersCodeSysproJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CustomersCodeSysproRoute,
} as any)
const CustomersCodeSysproLicenseRoute =
  CustomersCodeSysproLicenseRouteImport.update({
    id: '/license',
    path: '/license',
    getParentRoute: () => CustomersCodeSysproRoute,
  } as any)
const CustomersCodeSysproOperatorsRoute =
  CustomersCodeSysproOperatorsRouteImport.update({
    id: '/operators',
    path: '/operators',
    getParentRoute: () => CustomersCodeSysproRoute,
  } as any)
const CustomersCodeSysproSecurityRoute =
  CustomersCodeSysproSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => CustomersCodeSysproRoute,
  } as any)
const CustomersCodeSysproSlaRoute = CustomersCodeSysproSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => CustomersCodeSysproRoute,
} as any)
const CustomersCodeSysproSqlRoute = CustomersCodeSysproSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => CustomersCodeSysproRoute,
} as any)
const CustomersCodeTicketsIndexRoute =
  CustomersCodeTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CustomersCodeTicketsRoute,
  } as any)
const CustomersCodeTicketsClosedRoute =
  CustomersCodeTicketsClosedRouteImport.update({
    id: '/closed',
    path: '/closed',
    getParentRoute: () => CustomersCodeTicketsRoute,
  } as any)
const CustomersCodeTicketsOpenRoute =
  CustomersCodeTicketsOpenRouteImport.update({
    id: '/open',
    path: '/open',
    getParentRoute: () => CustomersCodeTicketsRoute,
  } as any)
const CustomersCodeTicketsResolvedRoute =
  CustomersCodeTicketsResolvedRouteImport.update({
    id: '/resolved',
    path: '/resolved',
    getParentRoute: () => CustomersCodeTicketsRoute,
  } as any)
const CustomersCodeTicketsSlaRoute = CustomersCodeTicketsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => CustomersCodeTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-pack': typeof GetPackRoute
  '/login': typeof LoginRoute
  '/pack': typeof PackRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/ui-lab': typeof UiLabRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/api/iops': typeof ApiIopsRoute
  '/api/patches': typeof ApiPatchesRoute
  '/api/portfolio-refresh': typeof ApiPortfolioRefreshRoute
  '/api/report-preview': typeof ApiReportPreviewRoute
  '/customers/$code': typeof CustomersCodeRouteWithChildren
  '/downloads/$': typeof DownloadsSplatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/chrome': typeof SettingsChromeRoute
  '/settings/collect': typeof SettingsCollectRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/infrastructure': typeof SettingsInfrastructureRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/labels': typeof SettingsLabelsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/query': typeof SettingsQueryRoute
  '/settings/rag': typeof SettingsRagRoute
  '/settings/reports': typeof SettingsReportsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/smtp': typeof SettingsSmtpRoute
  '/settings/sql': typeof SettingsSqlRoute
  '/settings/ssl': typeof SettingsSslRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/agent-pack/$code': typeof ApiAgentPackCodeRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/onboard': typeof ApiAgentOnboardRoute
  '/api/agent/pack': typeof ApiAgentPackRoute
  '/api/agent/sync': typeof ApiAgentSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-report': typeof ApiCronWeeklyReportRoute
  '/api/pulseway/webhook': typeof ApiPulsewayWebhookRoute
  '/api/wp/estate': typeof ApiWpEstateRoute
  '/customers/$code/ams': typeof CustomersCodeAmsRouteWithChildren
  '/customers/$code/cove': typeof CustomersCodeCoveRouteWithChildren
  '/customers/$code/csp': typeof CustomersCodeCspRouteWithChildren
  '/customers/$code/epp': typeof CustomersCodeEppRouteWithChildren
  '/customers/$code/rmm': typeof CustomersCodeRmmRouteWithChildren
  '/customers/$code/syspro': typeof CustomersCodeSysproRouteWithChildren
  '/customers/$code/tickets': typeof CustomersCodeTicketsRouteWithChildren
  '/customers/$code/': typeof CustomersCodeIndexRoute
  '/customers/$code/ams/change': typeof CustomersCodeAmsChangeRoute
  '/customers/$code/ams/incidents': typeof CustomersCodeAmsIncidentsRoute
  '/customers/$code/ams/risks': typeof CustomersCodeAmsRisksRoute
  '/customers/$code/ams/sla': typeof CustomersCodeAmsSlaRoute
  '/customers/$code/cove/devices': typeof CustomersCodeCoveDevicesRoute
  '/customers/$code/cove/mapping': typeof CustomersCodeCoveMappingRoute
  '/customers/$code/cove/overview': typeof CustomersCodeCoveOverviewRoute
  '/customers/$code/cove/recovery': typeof CustomersCodeCoveRecoveryRoute
  '/customers/$code/cove/retention': typeof CustomersCodeCoveRetentionRoute
  '/customers/$code/cove/sla': typeof CustomersCodeCoveSlaRoute
  '/customers/$code/csp/global-admins': typeof CustomersCodeCspGlobalAdminsRoute
  '/customers/$code/csp/licenses': typeof CustomersCodeCspLicensesRoute
  '/customers/$code/csp/mfa': typeof CustomersCodeCspMfaRoute
  '/customers/$code/csp/secure-score': typeof CustomersCodeCspSecureScoreRoute
  '/customers/$code/csp/users': typeof CustomersCodeCspUsersRoute
  '/customers/$code/epp/endpoints': typeof CustomersCodeEppEndpointsRoute
  '/customers/$code/epp/incidents': typeof CustomersCodeEppIncidentsRoute
  '/customers/$code/epp/modules': typeof CustomersCodeEppModulesRoute
  '/customers/$code/epp/quarantine': typeof CustomersCodeEppQuarantineRoute
  '/customers/$code/epp/sla': typeof CustomersCodeEppSlaRoute
  '/customers/$code/rmm/alerts': typeof CustomersCodeRmmAlertsRoute
  '/customers/$code/rmm/devices': typeof CustomersCodeRmmDevicesRoute
  '/customers/$code/rmm/events': typeof CustomersCodeRmmEventsRoute
  '/customers/$code/rmm/iops': typeof CustomersCodeRmmIopsRoute
  '/customers/$code/rmm/mapping': typeof CustomersCodeRmmMappingRoute
  '/customers/$code/rmm/overview': typeof CustomersCodeRmmOverviewRoute
  '/customers/$code/rmm/patch': typeof CustomersCodeRmmPatchRoute
  '/customers/$code/rmm/sla': typeof CustomersCodeRmmSlaRoute
  '/customers/$code/rmm/workstations': typeof CustomersCodeRmmWorkstationsRoute
  '/customers/$code/syspro/day-end': typeof CustomersCodeSysproDayEndRoute
  '/customers/$code/syspro/dtr': typeof CustomersCodeSysproDtrRoute
  '/customers/$code/syspro/health': typeof CustomersCodeSysproHealthRoute
  '/customers/$code/syspro/hotfixes': typeof CustomersCodeSysproHotfixesRoute
  '/customers/$code/syspro/jobs': typeof CustomersCodeSysproJobsRoute
  '/customers/$code/syspro/license': typeof CustomersCodeSysproLicenseRoute
  '/customers/$code/syspro/operators': typeof CustomersCodeSysproOperatorsRoute
  '/customers/$code/syspro/security': typeof CustomersCodeSysproSecurityRoute
  '/customers/$code/syspro/sla': typeof CustomersCodeSysproSlaRoute
  '/customers/$code/syspro/sql': typeof CustomersCodeSysproSqlRoute
  '/customers/$code/tickets/closed': typeof CustomersCodeTicketsClosedRoute
  '/customers/$code/tickets/open': typeof CustomersCodeTicketsOpenRoute
  '/customers/$code/tickets/resolved': typeof CustomersCodeTicketsResolvedRoute
  '/customers/$code/tickets/sla': typeof CustomersCodeTicketsSlaRoute
  '/customers/$code/ams/': typeof CustomersCodeAmsIndexRoute
  '/customers/$code/cove/': typeof CustomersCodeCoveIndexRoute
  '/customers/$code/csp/': typeof CustomersCodeCspIndexRoute
  '/customers/$code/epp/': typeof CustomersCodeEppIndexRoute
  '/customers/$code/rmm/': typeof CustomersCodeRmmIndexRoute
  '/customers/$code/syspro/': typeof CustomersCodeSysproIndexRoute
  '/customers/$code/tickets/': typeof CustomersCodeTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-pack': typeof GetPackRoute
  '/login': typeof LoginRoute
  '/pack': typeof PackRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/two-factor': typeof TwoFactorRoute
  '/ui-lab': typeof UiLabRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/api/iops': typeof ApiIopsRoute
  '/api/patches': typeof ApiPatchesRoute
  '/api/portfolio-refresh': typeof ApiPortfolioRefreshRoute
  '/api/report-preview': typeof ApiReportPreviewRoute
  '/downloads/$': typeof DownloadsSplatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/chrome': typeof SettingsChromeRoute
  '/settings/collect': typeof SettingsCollectRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/infrastructure': typeof SettingsInfrastructureRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/labels': typeof SettingsLabelsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/query': typeof SettingsQueryRoute
  '/settings/rag': typeof SettingsRagRoute
  '/settings/reports': typeof SettingsReportsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/smtp': typeof SettingsSmtpRoute
  '/settings/sql': typeof SettingsSqlRoute
  '/settings/ssl': typeof SettingsSslRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings': typeof SettingsIndexRoute
  '/api/agent-pack/$code': typeof ApiAgentPackCodeRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/onboard': typeof ApiAgentOnboardRoute
  '/api/agent/pack': typeof ApiAgentPackRoute
  '/api/agent/sync': typeof ApiAgentSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-report': typeof ApiCronWeeklyReportRoute
  '/api/pulseway/webhook': typeof ApiPulsewayWebhookRoute
  '/api/wp/estate': typeof ApiWpEstateRoute
  '/customers/$code': typeof CustomersCodeIndexRoute
  '/customers/$code/ams/change': typeof CustomersCodeAmsChangeRoute
  '/customers/$code/ams/incidents': typeof CustomersCodeAmsIncidentsRoute
  '/customers/$code/ams/risks': typeof CustomersCodeAmsRisksRoute
  '/customers/$code/ams/sla': typeof CustomersCodeAmsSlaRoute
  '/customers/$code/cove/devices': typeof CustomersCodeCoveDevicesRoute
  '/customers/$code/cove/mapping': typeof CustomersCodeCoveMappingRoute
  '/customers/$code/cove/overview': typeof CustomersCodeCoveOverviewRoute
  '/customers/$code/cove/recovery': typeof CustomersCodeCoveRecoveryRoute
  '/customers/$code/cove/retention': typeof CustomersCodeCoveRetentionRoute
  '/customers/$code/cove/sla': typeof CustomersCodeCoveSlaRoute
  '/customers/$code/csp/global-admins': typeof CustomersCodeCspGlobalAdminsRoute
  '/customers/$code/csp/licenses': typeof CustomersCodeCspLicensesRoute
  '/customers/$code/csp/mfa': typeof CustomersCodeCspMfaRoute
  '/customers/$code/csp/secure-score': typeof CustomersCodeCspSecureScoreRoute
  '/customers/$code/csp/users': typeof CustomersCodeCspUsersRoute
  '/customers/$code/epp/endpoints': typeof CustomersCodeEppEndpointsRoute
  '/customers/$code/epp/incidents': typeof CustomersCodeEppIncidentsRoute
  '/customers/$code/epp/modules': typeof CustomersCodeEppModulesRoute
  '/customers/$code/epp/quarantine': typeof CustomersCodeEppQuarantineRoute
  '/customers/$code/epp/sla': typeof CustomersCodeEppSlaRoute
  '/customers/$code/rmm/alerts': typeof CustomersCodeRmmAlertsRoute
  '/customers/$code/rmm/devices': typeof CustomersCodeRmmDevicesRoute
  '/customers/$code/rmm/events': typeof CustomersCodeRmmEventsRoute
  '/customers/$code/rmm/iops': typeof CustomersCodeRmmIopsRoute
  '/customers/$code/rmm/mapping': typeof CustomersCodeRmmMappingRoute
  '/customers/$code/rmm/overview': typeof CustomersCodeRmmOverviewRoute
  '/customers/$code/rmm/patch': typeof CustomersCodeRmmPatchRoute
  '/customers/$code/rmm/sla': typeof CustomersCodeRmmSlaRoute
  '/customers/$code/rmm/workstations': typeof CustomersCodeRmmWorkstationsRoute
  '/customers/$code/syspro/day-end': typeof CustomersCodeSysproDayEndRoute
  '/customers/$code/syspro/dtr': typeof CustomersCodeSysproDtrRoute
  '/customers/$code/syspro/health': typeof CustomersCodeSysproHealthRoute
  '/customers/$code/syspro/hotfixes': typeof CustomersCodeSysproHotfixesRoute
  '/customers/$code/syspro/jobs': typeof CustomersCodeSysproJobsRoute
  '/customers/$code/syspro/license': typeof CustomersCodeSysproLicenseRoute
  '/customers/$code/syspro/operators': typeof CustomersCodeSysproOperatorsRoute
  '/customers/$code/syspro/security': typeof CustomersCodeSysproSecurityRoute
  '/customers/$code/syspro/sla': typeof CustomersCodeSysproSlaRoute
  '/customers/$code/syspro/sql': typeof CustomersCodeSysproSqlRoute
  '/customers/$code/tickets/closed': typeof CustomersCodeTicketsClosedRoute
  '/customers/$code/tickets/open': typeof CustomersCodeTicketsOpenRoute
  '/customers/$code/tickets/resolved': typeof CustomersCodeTicketsResolvedRoute
  '/customers/$code/tickets/sla': typeof CustomersCodeTicketsSlaRoute
  '/customers/$code/ams': typeof CustomersCodeAmsIndexRoute
  '/customers/$code/cove': typeof CustomersCodeCoveIndexRoute
  '/customers/$code/csp': typeof CustomersCodeCspIndexRoute
  '/customers/$code/epp': typeof CustomersCodeEppIndexRoute
  '/customers/$code/rmm': typeof CustomersCodeRmmIndexRoute
  '/customers/$code/syspro': typeof CustomersCodeSysproIndexRoute
  '/customers/$code/tickets': typeof CustomersCodeTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-pack': typeof GetPackRoute
  '/login': typeof LoginRoute
  '/pack': typeof PackRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/ui-lab': typeof UiLabRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/api/iops': typeof ApiIopsRoute
  '/api/patches': typeof ApiPatchesRoute
  '/api/portfolio-refresh': typeof ApiPortfolioRefreshRoute
  '/api/report-preview': typeof ApiReportPreviewRoute
  '/customers/$code': typeof CustomersCodeRouteWithChildren
  '/downloads/$': typeof DownloadsSplatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/chrome': typeof SettingsChromeRoute
  '/settings/collect': typeof SettingsCollectRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/infrastructure': typeof SettingsInfrastructureRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/labels': typeof SettingsLabelsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/query': typeof SettingsQueryRoute
  '/settings/rag': typeof SettingsRagRoute
  '/settings/reports': typeof SettingsReportsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/smtp': typeof SettingsSmtpRoute
  '/settings/sql': typeof SettingsSqlRoute
  '/settings/ssl': typeof SettingsSslRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/agent-pack/$code': typeof ApiAgentPackCodeRoute
  '/api/agent/heartbeat': typeof ApiAgentHeartbeatRoute
  '/api/agent/onboard': typeof ApiAgentOnboardRoute
  '/api/agent/pack': typeof ApiAgentPackRoute
  '/api/agent/sync': typeof ApiAgentSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-report': typeof ApiCronWeeklyReportRoute
  '/api/pulseway/webhook': typeof ApiPulsewayWebhookRoute
  '/api/wp/estate': typeof ApiWpEstateRoute
  '/customers/$code/ams': typeof CustomersCodeAmsRouteWithChildren
  '/customers/$code/cove': typeof CustomersCodeCoveRouteWithChildren
  '/customers/$code/csp': typeof CustomersCodeCspRouteWithChildren
  '/customers/$code/epp': typeof CustomersCodeEppRouteWithChildren
  '/customers/$code/rmm': typeof CustomersCodeRmmRouteWithChildren
  '/customers/$code/syspro': typeof CustomersCodeSysproRouteWithChildren
  '/customers/$code/tickets': typeof CustomersCodeTicketsRouteWithChildren
  '/customers/$code/': typeof CustomersCodeIndexRoute
  '/customers/$code/ams/change': typeof CustomersCodeAmsChangeRoute
  '/customers/$code/ams/incidents': typeof CustomersCodeAmsIncidentsRoute
  '/customers/$code/ams/risks': typeof CustomersCodeAmsRisksRoute
  '/customers/$code/ams/sla': typeof CustomersCodeAmsSlaRoute
  '/customers/$code/cove/devices': typeof CustomersCodeCoveDevicesRoute
  '/customers/$code/cove/mapping': typeof CustomersCodeCoveMappingRoute
  '/customers/$code/cove/overview': typeof CustomersCodeCoveOverviewRoute
  '/customers/$code/cove/recovery': typeof CustomersCodeCoveRecoveryRoute
  '/customers/$code/cove/retention': typeof CustomersCodeCoveRetentionRoute
  '/customers/$code/cove/sla': typeof CustomersCodeCoveSlaRoute
  '/customers/$code/csp/global-admins': typeof CustomersCodeCspGlobalAdminsRoute
  '/customers/$code/csp/licenses': typeof CustomersCodeCspLicensesRoute
  '/customers/$code/csp/mfa': typeof CustomersCodeCspMfaRoute
  '/customers/$code/csp/secure-score': typeof CustomersCodeCspSecureScoreRoute
  '/customers/$code/csp/users': typeof CustomersCodeCspUsersRoute
  '/customers/$code/epp/endpoints': typeof CustomersCodeEppEndpointsRoute
  '/customers/$code/epp/incidents': typeof CustomersCodeEppIncidentsRoute
  '/customers/$code/epp/modules': typeof CustomersCodeEppModulesRoute
  '/customers/$code/epp/quarantine': typeof CustomersCodeEppQuarantineRoute
  '/customers/$code/epp/sla': typeof CustomersCodeEppSlaRoute
  '/customers/$code/rmm/alerts': typeof CustomersCodeRmmAlertsRoute
  '/customers/$code/rmm/devices': typeof CustomersCodeRmmDevicesRoute
  '/customers/$code/rmm/events': typeof CustomersCodeRmmEventsRoute
  '/customers/$code/rmm/iops': typeof CustomersCodeRmmIopsRoute
  '/customers/$code/rmm/mapping': typeof CustomersCodeRmmMappingRoute
  '/customers/$code/rmm/overview': typeof CustomersCodeRmmOverviewRoute
  '/customers/$code/rmm/patch': typeof CustomersCodeRmmPatchRoute
  '/customers/$code/rmm/sla': typeof CustomersCodeRmmSlaRoute
  '/customers/$code/rmm/workstations': typeof CustomersCodeRmmWorkstationsRoute
  '/customers/$code/syspro/day-end': typeof CustomersCodeSysproDayEndRoute
  '/customers/$code/syspro/dtr': typeof CustomersCodeSysproDtrRoute
  '/customers/$code/syspro/health': typeof CustomersCodeSysproHealthRoute
  '/customers/$code/syspro/hotfixes': typeof CustomersCodeSysproHotfixesRoute
  '/customers/$code/syspro/jobs': typeof CustomersCodeSysproJobsRoute
  '/customers/$code/syspro/license': typeof CustomersCodeSysproLicenseRoute
  '/customers/$code/syspro/operators': typeof CustomersCodeSysproOperatorsRoute
  '/customers/$code/syspro/security': typeof CustomersCodeSysproSecurityRoute
  '/customers/$code/syspro/sla': typeof CustomersCodeSysproSlaRoute
  '/customers/$code/syspro/sql': typeof CustomersCodeSysproSqlRoute
  '/customers/$code/tickets/closed': typeof CustomersCodeTicketsClosedRoute
  '/customers/$code/tickets/open': typeof CustomersCodeTicketsOpenRoute
  '/customers/$code/tickets/resolved': typeof CustomersCodeTicketsResolvedRoute
  '/customers/$code/tickets/sla': typeof CustomersCodeTicketsSlaRoute
  '/customers/$code/ams/': typeof CustomersCodeAmsIndexRoute
  '/customers/$code/cove/': typeof CustomersCodeCoveIndexRoute
  '/customers/$code/csp/': typeof CustomersCodeCspIndexRoute
  '/customers/$code/epp/': typeof CustomersCodeEppIndexRoute
  '/customers/$code/rmm/': typeof CustomersCodeRmmIndexRoute
  '/customers/$code/syspro/': typeof CustomersCodeSysproIndexRoute
  '/customers/$code/tickets/': typeof CustomersCodeTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-pack'
    | '/login'
    | '/pack'
    | '/reports'
    | '/security'
    | '/settings'
    | '/two-factor'
    | '/ui-lab'
    | '/api/bootstrap-admin'
    | '/api/iops'
    | '/api/patches'
    | '/api/portfolio-refresh'
    | '/api/report-preview'
    | '/customers/$code'
    | '/downloads/$'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/alerts'
    | '/settings/audit'
    | '/settings/chrome'
    | '/settings/collect'
    | '/settings/dashboard'
    | '/settings/infrastructure'
    | '/settings/integrations'
    | '/settings/labels'
    | '/settings/profile'
    | '/settings/query'
    | '/settings/rag'
    | '/settings/reports'
    | '/settings/security'
    | '/settings/smtp'
    | '/settings/sql'
    | '/settings/ssl'
    | '/settings/theme'
    | '/settings/users'
    | '/settings/'
    | '/api/agent-pack/$code'
    | '/api/agent/heartbeat'
    | '/api/agent/onboard'
    | '/api/agent/pack'
    | '/api/agent/sync'
    | '/api/auth/$'
    | '/api/cron/weekly-report'
    | '/api/pulseway/webhook'
    | '/api/wp/estate'
    | '/customers/$code/ams'
    | '/customers/$code/cove'
    | '/customers/$code/csp'
    | '/customers/$code/epp'
    | '/customers/$code/rmm'
    | '/customers/$code/syspro'
    | '/customers/$code/tickets'
    | '/customers/$code/'
    | '/customers/$code/ams/change'
    | '/customers/$code/ams/incidents'
    | '/customers/$code/ams/risks'
    | '/customers/$code/ams/sla'
    | '/customers/$code/cove/devices'
    | '/customers/$code/cove/mapping'
    | '/customers/$code/cove/overview'
    | '/customers/$code/cove/recovery'
    | '/customers/$code/cove/retention'
    | '/customers/$code/cove/sla'
    | '/customers/$code/csp/global-admins'
    | '/customers/$code/csp/licenses'
    | '/customers/$code/csp/mfa'
    | '/customers/$code/csp/secure-score'
    | '/customers/$code/csp/users'
    | '/customers/$code/epp/endpoints'
    | '/customers/$code/epp/incidents'
    | '/customers/$code/epp/modules'
    | '/customers/$code/epp/quarantine'
    | '/customers/$code/epp/sla'
    | '/customers/$code/rmm/alerts'
    | '/customers/$code/rmm/devices'
    | '/customers/$code/rmm/events'
    | '/customers/$code/rmm/iops'
    | '/customers/$code/rmm/mapping'
    | '/customers/$code/rmm/overview'
    | '/customers/$code/rmm/patch'
    | '/customers/$code/rmm/sla'
    | '/customers/$code/rmm/workstations'
    | '/customers/$code/syspro/day-end'
    | '/customers/$code/syspro/dtr'
    | '/customers/$code/syspro/health'
    | '/customers/$code/syspro/hotfixes'
    | '/customers/$code/syspro/jobs'
    | '/customers/$code/syspro/license'
    | '/customers/$code/syspro/operators'
    | '/customers/$code/syspro/security'
    | '/customers/$code/syspro/sla'
    | '/customers/$code/syspro/sql'
    | '/customers/$code/tickets/closed'
    | '/customers/$code/tickets/open'
    | '/customers/$code/tickets/resolved'
    | '/customers/$code/tickets/sla'
    | '/customers/$code/ams/'
    | '/customers/$code/cove/'
    | '/customers/$code/csp/'
    | '/customers/$code/epp/'
    | '/customers/$code/rmm/'
    | '/customers/$code/syspro/'
    | '/customers/$code/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-pack'
    | '/login'
    | '/pack'
    | '/reports'
    | '/security'
    | '/two-factor'
    | '/ui-lab'
    | '/api/bootstrap-admin'
    | '/api/iops'
    | '/api/patches'
    | '/api/portfolio-refresh'
    | '/api/report-preview'
    | '/downloads/$'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/alerts'
    | '/settings/audit'
    | '/settings/chrome'
    | '/settings/collect'
    | '/settings/dashboard'
    | '/settings/infrastructure'
    | '/settings/integrations'
    | '/settings/labels'
    | '/settings/profile'
    | '/settings/query'
    | '/settings/rag'
    | '/settings/reports'
    | '/settings/security'
    | '/settings/smtp'
    | '/settings/sql'
    | '/settings/ssl'
    | '/settings/theme'
    | '/settings/users'
    | '/settings'
    | '/api/agent-pack/$code'
    | '/api/agent/heartbeat'
    | '/api/agent/onboard'
    | '/api/agent/pack'
    | '/api/agent/sync'
    | '/api/auth/$'
    | '/api/cron/weekly-report'
    | '/api/pulseway/webhook'
    | '/api/wp/estate'
    | '/customers/$code'
    | '/customers/$code/ams/change'
    | '/customers/$code/ams/incidents'
    | '/customers/$code/ams/risks'
    | '/customers/$code/ams/sla'
    | '/customers/$code/cove/devices'
    | '/customers/$code/cove/mapping'
    | '/customers/$code/cove/overview'
    | '/customers/$code/cove/recovery'
    | '/customers/$code/cove/retention'
    | '/customers/$code/cove/sla'
    | '/customers/$code/csp/global-admins'
    | '/customers/$code/csp/licenses'
    | '/customers/$code/csp/mfa'
    | '/customers/$code/csp/secure-score'
    | '/customers/$code/csp/users'
    | '/customers/$code/epp/endpoints'
    | '/customers/$code/epp/incidents'
    | '/customers/$code/epp/modules'
    | '/customers/$code/epp/quarantine'
    | '/customers/$code/epp/sla'
    | '/customers/$code/rmm/alerts'
    | '/customers/$code/rmm/devices'
    | '/customers/$code/rmm/events'
    | '/customers/$code/rmm/iops'
    | '/customers/$code/rmm/mapping'
    | '/customers/$code/rmm/overview'
    | '/customers/$code/rmm/patch'
    | '/customers/$code/rmm/sla'
    | '/customers/$code/rmm/workstations'
    | '/customers/$code/syspro/day-end'
    | '/customers/$code/syspro/dtr'
    | '/customers/$code/syspro/health'
    | '/customers/$code/syspro/hotfixes'
    | '/customers/$code/syspro/jobs'
    | '/customers/$code/syspro/license'
    | '/customers/$code/syspro/operators'
    | '/customers/$code/syspro/security'
    | '/customers/$code/syspro/sla'
    | '/customers/$code/syspro/sql'
    | '/customers/$code/tickets/closed'
    | '/customers/$code/tickets/open'
    | '/customers/$code/tickets/resolved'
    | '/customers/$code/tickets/sla'
    | '/customers/$code/ams'
    | '/customers/$code/cove'
    | '/customers/$code/csp'
    | '/customers/$code/epp'
    | '/customers/$code/rmm'
    | '/customers/$code/syspro'
    | '/customers/$code/tickets'
  id:
    | '__root__'
    | '/'
    | '/get-pack'
    | '/login'
    | '/pack'
    | '/reports'
    | '/security'
    | '/settings'
    | '/two-factor'
    | '/ui-lab'
    | '/api/bootstrap-admin'
    | '/api/iops'
    | '/api/patches'
    | '/api/portfolio-refresh'
    | '/api/report-preview'
    | '/customers/$code'
    | '/downloads/$'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/alerts'
    | '/settings/audit'
    | '/settings/chrome'
    | '/settings/collect'
    | '/settings/dashboard'
    | '/settings/infrastructure'
    | '/settings/integrations'
    | '/settings/labels'
    | '/settings/profile'
    | '/settings/query'
    | '/settings/rag'
    | '/settings/reports'
    | '/settings/security'
    | '/settings/smtp'
    | '/settings/sql'
    | '/settings/ssl'
    | '/settings/theme'
    | '/settings/users'
    | '/settings/'
    | '/api/agent-pack/$code'
    | '/api/agent/heartbeat'
    | '/api/agent/onboard'
    | '/api/agent/pack'
    | '/api/agent/sync'
    | '/api/auth/$'
    | '/api/cron/weekly-report'
    | '/api/pulseway/webhook'
    | '/api/wp/estate'
    | '/customers/$code/ams'
    | '/customers/$code/cove'
    | '/customers/$code/csp'
    | '/customers/$code/epp'
    | '/customers/$code/rmm'
    | '/customers/$code/syspro'
    | '/customers/$code/tickets'
    | '/customers/$code/'
    | '/customers/$code/ams/change'
    | '/customers/$code/ams/incidents'
    | '/customers/$code/ams/risks'
    | '/customers/$code/ams/sla'
    | '/customers/$code/cove/devices'
    | '/customers/$code/cove/mapping'
    | '/customers/$code/cove/overview'
    | '/customers/$code/cove/recovery'
    | '/customers/$code/cove/retention'
    | '/customers/$code/cove/sla'
    | '/customers/$code/csp/global-admins'
    | '/customers/$code/csp/licenses'
    | '/customers/$code/csp/mfa'
    | '/customers/$code/csp/secure-score'
    | '/customers/$code/csp/users'
    | '/customers/$code/epp/endpoints'
    | '/customers/$code/epp/incidents'
    | '/customers/$code/epp/modules'
    | '/customers/$code/epp/quarantine'
    | '/customers/$code/epp/sla'
    | '/customers/$code/rmm/alerts'
    | '/customers/$code/rmm/devices'
    | '/customers/$code/rmm/events'
    | '/customers/$code/rmm/iops'
    | '/customers/$code/rmm/mapping'
    | '/customers/$code/rmm/overview'
    | '/customers/$code/rmm/patch'
    | '/customers/$code/rmm/sla'
    | '/customers/$code/rmm/workstations'
    | '/customers/$code/syspro/day-end'
    | '/customers/$code/syspro/dtr'
    | '/customers/$code/syspro/health'
    | '/customers/$code/syspro/hotfixes'
    | '/customers/$code/syspro/jobs'
    | '/customers/$code/syspro/license'
    | '/customers/$code/syspro/operators'
    | '/customers/$code/syspro/security'
    | '/customers/$code/syspro/sla'
    | '/customers/$code/syspro/sql'
    | '/customers/$code/tickets/closed'
    | '/customers/$code/tickets/open'
    | '/customers/$code/tickets/resolved'
    | '/customers/$code/tickets/sla'
    | '/customers/$code/ams/'
    | '/customers/$code/cove/'
    | '/customers/$code/csp/'
    | '/customers/$code/epp/'
    | '/customers/$code/rmm/'
    | '/customers/$code/syspro/'
    | '/customers/$code/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetPackRoute: typeof GetPackRoute
  LoginRoute: typeof LoginRoute
  PackRoute: typeof PackRoute
  ReportsRoute: typeof ReportsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TwoFactorRoute: typeof TwoFactorRoute
  UiLabRoute: typeof UiLabRoute
  ApiBootstrapAdminRoute: typeof ApiBootstrapAdminRoute
  ApiIopsRoute: typeof ApiIopsRoute
  ApiPatchesRoute: typeof ApiPatchesRoute
  ApiPortfolioRefreshRoute: typeof ApiPortfolioRefreshRoute
  ApiReportPreviewRoute: typeof ApiReportPreviewRoute
  CustomersCodeRoute: typeof CustomersCodeRouteWithChildren
  DownloadsSplatRoute: typeof DownloadsSplatRoute
  ApiAgentPackCodeRoute: typeof ApiAgentPackCodeRoute
  ApiAgentHeartbeatRoute: typeof ApiAgentHeartbeatRoute
  ApiAgentOnboardRoute: typeof ApiAgentOnboardRoute
  ApiAgentPackRoute: typeof ApiAgentPackRoute
  ApiAgentSyncRoute: typeof ApiAgentSyncRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronWeeklyReportRoute: typeof ApiCronWeeklyReportRoute
  ApiPulsewayWebhookRoute: typeof ApiPulsewayWebhookRoute
  ApiWpEstateRoute: typeof ApiWpEstateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-pack': {
      id: '/get-pack'
      path: '/get-pack'
      fullPath: '/get-pack'
      preLoaderRoute: typeof GetPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-lab': {
      id: '/ui-lab'
      path: '/ui-lab'
      fullPath: '/ui-lab'
      preLoaderRoute: typeof UiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap-admin': {
      id: '/api/bootstrap-admin'
      path: '/api/bootstrap-admin'
      fullPath: '/api/bootstrap-admin'
      preLoaderRoute: typeof ApiBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iops': {
      id: '/api/iops'
      path: '/api/iops'
      fullPath: '/api/iops'
      preLoaderRoute: typeof ApiIopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patches': {
      id: '/api/patches'
      path: '/api/patches'
      fullPath: '/api/patches'
      preLoaderRoute: typeof ApiPatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio-refresh': {
      id: '/api/portfolio-refresh'
      path: '/api/portfolio-refresh'
      fullPath: '/api/portfolio-refresh'
      preLoaderRoute: typeof ApiPortfolioRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-preview': {
      id: '/api/report-preview'
      path: '/api/report-preview'
      fullPath: '/api/report-preview'
      preLoaderRoute: typeof ApiReportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$code': {
      id: '/customers/$code'
      path: '/customers/$code'
      fullPath: '/customers/$code'
      preLoaderRoute: typeof CustomersCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/$': {
      id: '/downloads/$'
      path: '/downloads/$'
      fullPath: '/downloads/$'
      preLoaderRoute: typeof DownloadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/alerts': {
      id: '/settings/alerts'
      path: '/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof SettingsAlertsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/chrome': {
      id: '/settings/chrome'
      path: '/chrome'
      fullPath: '/settings/chrome'
      preLoaderRoute: typeof SettingsChromeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/collect': {
      id: '/settings/collect'
      path: '/collect'
      fullPath: '/settings/collect'
      preLoaderRoute: typeof SettingsCollectRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dashboard': {
      id: '/settings/dashboard'
      path: '/dashboard'
      fullPath: '/settings/dashboard'
      preLoaderRoute: typeof SettingsDashboardRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/infrastructure': {
      id: '/settings/infrastructure'
      path: '/infrastructure'
      fullPath: '/settings/infrastructure'
      preLoaderRoute: typeof SettingsInfrastructureRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/labels': {
      id: '/settings/labels'
      path: '/labels'
      fullPath: '/settings/labels'
      preLoaderRoute: typeof SettingsLabelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/query': {
      id: '/settings/query'
      path: '/query'
      fullPath: '/settings/query'
      preLoaderRoute: typeof SettingsQueryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rag': {
      id: '/settings/rag'
      path: '/rag'
      fullPath: '/settings/rag'
      preLoaderRoute: typeof SettingsRagRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/reports': {
      id: '/settings/reports'
      path: '/reports'
      fullPath: '/settings/reports'
      preLoaderRoute: typeof SettingsReportsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/smtp': {
      id: '/settings/smtp'
      path: '/smtp'
      fullPath: '/settings/smtp'
      preLoaderRoute: typeof SettingsSmtpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sql': {
      id: '/settings/sql'
      path: '/sql'
      fullPath: '/settings/sql'
      preLoaderRoute: typeof SettingsSqlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ssl': {
      id: '/settings/ssl'
      path: '/ssl'
      fullPath: '/settings/ssl'
      preLoaderRoute: typeof SettingsSslRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/agent-pack/$code': {
      id: '/api/agent-pack/$code'
      path: '/api/agent-pack/$code'
      fullPath: '/api/agent-pack/$code'
      preLoaderRoute: typeof ApiAgentPackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/heartbeat': {
      id: '/api/agent/heartbeat'
      path: '/api/agent/heartbeat'
      fullPath: '/api/agent/heartbeat'
      preLoaderRoute: typeof ApiAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/onboard': {
      id: '/api/agent/onboard'
      path: '/api/agent/onboard'
      fullPath: '/api/agent/onboard'
      preLoaderRoute: typeof ApiAgentOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/pack': {
      id: '/api/agent/pack'
      path: '/api/agent/pack'
      fullPath: '/api/agent/pack'
      preLoaderRoute: typeof ApiAgentPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/sync': {
      id: '/api/agent/sync'
      path: '/api/agent/sync'
      fullPath: '/api/agent/sync'
      preLoaderRoute: typeof ApiAgentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/weekly-report': {
      id: '/api/cron/weekly-report'
      path: '/api/cron/weekly-report'
      fullPath: '/api/cron/weekly-report'
      preLoaderRoute: typeof ApiCronWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulseway/webhook': {
      id: '/api/pulseway/webhook'
      path: '/api/pulseway/webhook'
      fullPath: '/api/pulseway/webhook'
      preLoaderRoute: typeof ApiPulsewayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wp/estate': {
      id: '/api/wp/estate'
      path: '/api/wp/estate'
      fullPath: '/api/wp/estate'
      preLoaderRoute: typeof ApiWpEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$code/': {
      id: '/customers/$code/'
      path: '/'
      fullPath: '/customers/$code/'
      preLoaderRoute: typeof CustomersCodeIndexRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/ams': {
      id: '/customers/$code/ams'
      path: '/ams'
      fullPath: '/customers/$code/ams'
      preLoaderRoute: typeof CustomersCodeAmsRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/cove': {
      id: '/customers/$code/cove'
      path: '/cove'
      fullPath: '/customers/$code/cove'
      preLoaderRoute: typeof CustomersCodeCoveRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/csp': {
      id: '/customers/$code/csp'
      path: '/csp'
      fullPath: '/customers/$code/csp'
      preLoaderRoute: typeof CustomersCodeCspRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/epp': {
      id: '/customers/$code/epp'
      path: '/epp'
      fullPath: '/customers/$code/epp'
      preLoaderRoute: typeof CustomersCodeEppRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/rmm': {
      id: '/customers/$code/rmm'
      path: '/rmm'
      fullPath: '/customers/$code/rmm'
      preLoaderRoute: typeof CustomersCodeRmmRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/syspro': {
      id: '/customers/$code/syspro'
      path: '/syspro'
      fullPath: '/customers/$code/syspro'
      preLoaderRoute: typeof CustomersCodeSysproRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/tickets': {
      id: '/customers/$code/tickets'
      path: '/tickets'
      fullPath: '/customers/$code/tickets'
      preLoaderRoute: typeof CustomersCodeTicketsRouteImport
      parentRoute: typeof CustomersCodeRoute
    }
    '/customers/$code/ams/': {
      id: '/customers/$code/ams/'
      path: '/'
      fullPath: '/customers/$code/ams/'
      preLoaderRoute: typeof CustomersCodeAmsIndexRouteImport
      parentRoute: typeof CustomersCodeAmsRoute
    }
    '/customers/$code/ams/change': {
      id: '/customers/$code/ams/change'
      path: '/change'
      fullPath: '/customers/$code/ams/change'
      preLoaderRoute: typeof CustomersCodeAmsChangeRouteImport
      parentRoute: typeof CustomersCodeAmsRoute
    }
    '/customers/$code/ams/incidents': {
      id: '/customers/$code/ams/incidents'
      path: '/incidents'
      fullPath: '/customers/$code/ams/incidents'
      preLoaderRoute: typeof CustomersCodeAmsIncidentsRouteImport
      parentRoute: typeof CustomersCodeAmsRoute
    }
    '/customers/$code/ams/risks': {
      id: '/customers/$code/ams/risks'
      path: '/risks'
      fullPath: '/customers/$code/ams/risks'
      preLoaderRoute: typeof CustomersCodeAmsRisksRouteImport
      parentRoute: typeof CustomersCodeAmsRoute
    }
    '/customers/$code/ams/sla': {
      id: '/customers/$code/ams/sla'
      path: '/sla'
      fullPath: '/customers/$code/ams/sla'
      preLoaderRoute: typeof CustomersCodeAmsSlaRouteImport
      parentRoute: typeof CustomersCodeAmsRoute
    }
    '/customers/$code/cove/': {
      id: '/customers/$code/cove/'
      path: '/'
      fullPath: '/customers/$code/cove/'
      preLoaderRoute: typeof CustomersCodeCoveIndexRouteImport
      parentRoute: typeof CustomersCodeCoveRoute
    }
    '/customers/$code/cove/devices': {
      id: '/customers/$code/cove/devices'
      path: '/devices'
      fullPath: '/customers/$code/cove/devices'
      preLoaderRoute: typeof CustomersCodeCoveDevicesRouteImport
      parentRoute: typeof CustomersCodeCoveRoute
    }
    '/customers/$code/cove/mapping': {
      id: '/customers/$code/cove/mapping'
      path: '/mapping'
      fullPath: '/customers/$code/cove/mapping'
      preLoaderRoute: typeof CustomersCodeCoveMappingRouteImport
      parentRoute: typeof CustomersCodeCoveRoute
    }
    '/customers/$code/cove/overview': {
      id: '/customers/$code/cove/overview'
      path: '/overview'
      fullPath: '/customers/$code/cove/overview'
      preLoaderRoute: typeof CustomersCodeCoveOverviewRouteImport
      parentRoute: typeof CustomersCodeCoveRoute
    }
    '/customers/$code/cove/recovery': {
      id: '/customers/$code/cove/recovery'
      path: '/recovery'
      fullPath: '/customers/$code/cove/recovery'
      preLoaderRoute: typeof CustomersCodeCoveRecoveryRouteImport
      parentRoute: typeof CustomersCodeCoveRoute
    }
    '/customers/$code/cove/retention': {
      id: '/customers/$code/cove/retention'
      path: '/retention'
      fullPath: '/customers/$code/cove/retention'
      preLoaderRoute: typeof CustomersCodeCoveRetentionRouteImport
      parentRoute: typeof CustomersCodeCoveRoute
    }
    '/customers/$code/cove/sla': {
      id: '/customers/$code/cove/sla'
      path: '/sla'
      fullPath: '/customers/$code/cove/sla'
      preLoaderRoute: typeof CustomersCodeCoveSlaRouteImport
      parentRoute: typeof CustomersCodeCoveRoute
    }
    '/customers/$code/csp/': {
      id: '/customers/$code/csp/'
      path: '/'
      fullPath: '/customers/$code/csp/'
      preLoaderRoute: typeof CustomersCodeCspIndexRouteImport
      parentRoute: typeof CustomersCodeCspRoute
    }
    '/customers/$code/csp/global-admins': {
      id: '/customers/$code/csp/global-admins'
      path: '/global-admins'
      fullPath: '/customers/$code/csp/global-admins'
      preLoaderRoute: typeof CustomersCodeCspGlobalAdminsRouteImport
      parentRoute: typeof CustomersCodeCspRoute
    }
    '/customers/$code/csp/licenses': {
      id: '/customers/$code/csp/licenses'
      path: '/licenses'
      fullPath: '/customers/$code/csp/licenses'
      preLoaderRoute: typeof CustomersCodeCspLicensesRouteImport
      parentRoute: typeof CustomersCodeCspRoute
    }
    '/customers/$code/csp/mfa': {
      id: '/customers/$code/csp/mfa'
      path: '/mfa'
      fullPath: '/customers/$code/csp/mfa'
      preLoaderRoute: typeof CustomersCodeCspMfaRouteImport
      parentRoute: typeof CustomersCodeCspRoute
    }
    '/customers/$code/csp/secure-score': {
      id: '/customers/$code/csp/secure-score'
      path: '/secure-score'
      fullPath: '/customers/$code/csp/secure-score'
      preLoaderRoute: typeof CustomersCodeCspSecureScoreRouteImport
      parentRoute: typeof CustomersCodeCspRoute
    }
    '/customers/$code/csp/users': {
      id: '/customers/$code/csp/users'
      path: '/users'
      fullPath: '/customers/$code/csp/users'
      preLoaderRoute: typeof CustomersCodeCspUsersRouteImport
      parentRoute: typeof CustomersCodeCspRoute
    }
    '/customers/$code/epp/': {
      id: '/customers/$code/epp/'
      path: '/'
      fullPath: '/customers/$code/epp/'
      preLoaderRoute: typeof CustomersCodeEppIndexRouteImport
      parentRoute: typeof CustomersCodeEppRoute
    }
    '/customers/$code/epp/endpoints': {
      id: '/customers/$code/epp/endpoints'
      path: '/endpoints'
      fullPath: '/customers/$code/epp/endpoints'
      preLoaderRoute: typeof CustomersCodeEppEndpointsRouteImport
      parentRoute: typeof CustomersCodeEppRoute
    }
    '/customers/$code/epp/incidents': {
      id: '/customers/$code/epp/incidents'
      path: '/incidents'
      fullPath: '/customers/$code/epp/incidents'
      preLoaderRoute: typeof CustomersCodeEppIncidentsRouteImport
      parentRoute: typeof CustomersCodeEppRoute
    }
    '/customers/$code/epp/modules': {
      id: '/customers/$code/epp/modules'
      path: '/modules'
      fullPath: '/customers/$code/epp/modules'
      preLoaderRoute: typeof CustomersCodeEppModulesRouteImport
      parentRoute: typeof CustomersCodeEppRoute
    }
    '/customers/$code/epp/quarantine': {
      id: '/customers/$code/epp/quarantine'
      path: '/quarantine'
      fullPath: '/customers/$code/epp/quarantine'
      preLoaderRoute: typeof CustomersCodeEppQuarantineRouteImport
      parentRoute: typeof CustomersCodeEppRoute
    }
    '/customers/$code/epp/sla': {
      id: '/customers/$code/epp/sla'
      path: '/sla'
      fullPath: '/customers/$code/epp/sla'
      preLoaderRoute: typeof CustomersCodeEppSlaRouteImport
      parentRoute: typeof CustomersCodeEppRoute
    }
    '/customers/$code/rmm/': {
      id: '/customers/$code/rmm/'
      path: '/'
      fullPath: '/customers/$code/rmm/'
      preLoaderRoute: typeof CustomersCodeRmmIndexRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/alerts': {
      id: '/customers/$code/rmm/alerts'
      path: '/alerts'
      fullPath: '/customers/$code/rmm/alerts'
      preLoaderRoute: typeof CustomersCodeRmmAlertsRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/devices': {
      id: '/customers/$code/rmm/devices'
      path: '/devices'
      fullPath: '/customers/$code/rmm/devices'
      preLoaderRoute: typeof CustomersCodeRmmDevicesRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/events': {
      id: '/customers/$code/rmm/events'
      path: '/events'
      fullPath: '/customers/$code/rmm/events'
      preLoaderRoute: typeof CustomersCodeRmmEventsRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/iops': {
      id: '/customers/$code/rmm/iops'
      path: '/iops'
      fullPath: '/customers/$code/rmm/iops'
      preLoaderRoute: typeof CustomersCodeRmmIopsRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/mapping': {
      id: '/customers/$code/rmm/mapping'
      path: '/mapping'
      fullPath: '/customers/$code/rmm/mapping'
      preLoaderRoute: typeof CustomersCodeRmmMappingRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/overview': {
      id: '/customers/$code/rmm/overview'
      path: '/overview'
      fullPath: '/customers/$code/rmm/overview'
      preLoaderRoute: typeof CustomersCodeRmmOverviewRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/patch': {
      id: '/customers/$code/rmm/patch'
      path: '/patch'
      fullPath: '/customers/$code/rmm/patch'
      preLoaderRoute: typeof CustomersCodeRmmPatchRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/sla': {
      id: '/customers/$code/rmm/sla'
      path: '/sla'
      fullPath: '/customers/$code/rmm/sla'
      preLoaderRoute: typeof CustomersCodeRmmSlaRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/rmm/workstations': {
      id: '/customers/$code/rmm/workstations'
      path: '/workstations'
      fullPath: '/customers/$code/rmm/workstations'
      preLoaderRoute: typeof CustomersCodeRmmWorkstationsRouteImport
      parentRoute: typeof CustomersCodeRmmRoute
    }
    '/customers/$code/syspro/': {
      id: '/customers/$code/syspro/'
      path: '/'
      fullPath: '/customers/$code/syspro/'
      preLoaderRoute: typeof CustomersCodeSysproIndexRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/day-end': {
      id: '/customers/$code/syspro/day-end'
      path: '/day-end'
      fullPath: '/customers/$code/syspro/day-end'
      preLoaderRoute: typeof CustomersCodeSysproDayEndRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/dtr': {
      id: '/customers/$code/syspro/dtr'
      path: '/dtr'
      fullPath: '/customers/$code/syspro/dtr'
      preLoaderRoute: typeof CustomersCodeSysproDtrRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/health': {
      id: '/customers/$code/syspro/health'
      path: '/health'
      fullPath: '/customers/$code/syspro/health'
      preLoaderRoute: typeof CustomersCodeSysproHealthRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/hotfixes': {
      id: '/customers/$code/syspro/hotfixes'
      path: '/hotfixes'
      fullPath: '/customers/$code/syspro/hotfixes'
      preLoaderRoute: typeof CustomersCodeSysproHotfixesRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/jobs': {
      id: '/customers/$code/syspro/jobs'
      path: '/jobs'
      fullPath: '/customers/$code/syspro/jobs'
      preLoaderRoute: typeof CustomersCodeSysproJobsRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/license': {
      id: '/customers/$code/syspro/license'
      path: '/license'
      fullPath: '/customers/$code/syspro/license'
      preLoaderRoute: typeof CustomersCodeSysproLicenseRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/operators': {
      id: '/customers/$code/syspro/operators'
      path: '/operators'
      fullPath: '/customers/$code/syspro/operators'
      preLoaderRoute: typeof CustomersCodeSysproOperatorsRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/security': {
      id: '/customers/$code/syspro/security'
      path: '/security'
      fullPath: '/customers/$code/syspro/security'
      preLoaderRoute: typeof CustomersCodeSysproSecurityRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/sla': {
      id: '/customers/$code/syspro/sla'
      path: '/sla'
      fullPath: '/customers/$code/syspro/sla'
      preLoaderRoute: typeof CustomersCodeSysproSlaRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/syspro/sql': {
      id: '/customers/$code/syspro/sql'
      path: '/sql'
      fullPath: '/customers/$code/syspro/sql'
      preLoaderRoute: typeof CustomersCodeSysproSqlRouteImport
      parentRoute: typeof CustomersCodeSysproRoute
    }
    '/customers/$code/tickets/': {
      id: '/customers/$code/tickets/'
      path: '/'
      fullPath: '/customers/$code/tickets/'
      preLoaderRoute: typeof CustomersCodeTicketsIndexRouteImport
      parentRoute: typeof CustomersCodeTicketsRoute
    }
    '/customers/$code/tickets/closed': {
      id: '/customers/$code/tickets/closed'
      path: '/closed'
      fullPath: '/customers/$code/tickets/closed'
      preLoaderRoute: typeof CustomersCodeTicketsClosedRouteImport
      parentRoute: typeof CustomersCodeTicketsRoute
    }
    '/customers/$code/tickets/open': {
      id: '/customers/$code/tickets/open'
      path: '/open'
      fullPath: '/customers/$code/tickets/open'
      preLoaderRoute: typeof CustomersCodeTicketsOpenRouteImport
      parentRoute: typeof CustomersCodeTicketsRoute
    }
    '/customers/$code/tickets/resolved': {
      id: '/customers/$code/tickets/resolved'
      path: '/resolved'
      fullPath: '/customers/$code/tickets/resolved'
      preLoaderRoute: typeof CustomersCodeTicketsResolvedRouteImport
      parentRoute: typeof CustomersCodeTicketsRoute
    }
    '/customers/$code/tickets/sla': {
      id: '/customers/$code/tickets/sla'
      path: '/sla'
      fullPath: '/customers/$code/tickets/sla'
      preLoaderRoute: typeof CustomersCodeTicketsSlaRouteImport
      parentRoute: typeof CustomersCodeTicketsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsAlertsRoute: typeof SettingsAlertsRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsChromeRoute: typeof SettingsChromeRoute
  SettingsCollectRoute: typeof SettingsCollectRoute
  SettingsDashboardRoute: typeof SettingsDashboardRoute
  SettingsInfrastructureRoute: typeof SettingsInfrastructureRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsLabelsRoute: typeof SettingsLabelsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsQueryRoute: typeof SettingsQueryRoute
  SettingsRagRoute: typeof SettingsRagRoute
  SettingsReportsRoute: typeof SettingsReportsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSmtpRoute: typeof SettingsSmtpRoute
  SettingsSqlRoute: typeof SettingsSqlRoute
  SettingsSslRoute: typeof SettingsSslRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsAlertsRoute: SettingsAlertsRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsChromeRoute: SettingsChromeRoute,
  SettingsCollectRoute: SettingsCollectRoute,
  SettingsDashboardRoute: SettingsDashboardRoute,
  SettingsInfrastructureRoute: SettingsInfrastructureRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsLabelsRoute: SettingsLabelsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsQueryRoute: SettingsQueryRoute,
  SettingsRagRoute: SettingsRagRoute,
  SettingsReportsRoute: SettingsReportsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSmtpRoute: SettingsSmtpRoute,
  SettingsSqlRoute: SettingsSqlRoute,
  SettingsSslRoute: SettingsSslRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface CustomersCodeAmsRouteChildren {
  CustomersCodeAmsChangeRoute: typeof CustomersCodeAmsChangeRoute
  CustomersCodeAmsIncidentsRoute: typeof CustomersCodeAmsIncidentsRoute
  CustomersCodeAmsRisksRoute: typeof CustomersCodeAmsRisksRoute
  CustomersCodeAmsSlaRoute: typeof CustomersCodeAmsSlaRoute
  CustomersCodeAmsIndexRoute: typeof CustomersCodeAmsIndexRoute
}

const CustomersCodeAmsRouteChildren: CustomersCodeAmsRouteChildren = {
  CustomersCodeAmsChangeRoute: CustomersCodeAmsChangeRoute,
  CustomersCodeAmsIncidentsRoute: CustomersCodeAmsIncidentsRoute,
  CustomersCodeAmsRisksRoute: CustomersCodeAmsRisksRoute,
  CustomersCodeAmsSlaRoute: CustomersCodeAmsSlaRoute,
  CustomersCodeAmsIndexRoute: CustomersCodeAmsIndexRoute,
}

const CustomersCodeAmsRouteWithChildren =
  CustomersCodeAmsRoute._addFileChildren(CustomersCodeAmsRouteChildren)

interface CustomersCodeCoveRouteChildren {
  CustomersCodeCoveDevicesRoute: typeof CustomersCodeCoveDevicesRoute
  CustomersCodeCoveMappingRoute: typeof CustomersCodeCoveMappingRoute
  CustomersCodeCoveOverviewRoute: typeof CustomersCodeCoveOverviewRoute
  CustomersCodeCoveRecoveryRoute: typeof CustomersCodeCoveRecoveryRoute
  CustomersCodeCoveRetentionRoute: typeof CustomersCodeCoveRetentionRoute
  CustomersCodeCoveSlaRoute: typeof CustomersCodeCoveSlaRoute
  CustomersCodeCoveIndexRoute: typeof CustomersCodeCoveIndexRoute
}

const CustomersCodeCoveRouteChildren: CustomersCodeCoveRouteChildren = {
  CustomersCodeCoveDevicesRoute: CustomersCodeCoveDevicesRoute,
  CustomersCodeCoveMappingRoute: CustomersCodeCoveMappingRoute,
  CustomersCodeCoveOverviewRoute: CustomersCodeCoveOverviewRoute,
  CustomersCodeCoveRecoveryRoute: CustomersCodeCoveRecoveryRoute,
  CustomersCodeCoveRetentionRoute: CustomersCodeCoveRetentionRoute,
  CustomersCodeCoveSlaRoute: CustomersCodeCoveSlaRoute,
  CustomersCodeCoveIndexRoute: CustomersCodeCoveIndexRoute,
}

const CustomersCodeCoveRouteWithChildren =
  CustomersCodeCoveRoute._addFileChildren(CustomersCodeCoveRouteChildren)

interface CustomersCodeCspRouteChildren {
  CustomersCodeCspGlobalAdminsRoute: typeof CustomersCodeCspGlobalAdminsRoute
  CustomersCodeCspLicensesRoute: typeof CustomersCodeCspLicensesRoute
  CustomersCodeCspMfaRoute: typeof CustomersCodeCspMfaRoute
  CustomersCodeCspSecureScoreRoute: typeof CustomersCodeCspSecureScoreRoute
  CustomersCodeCspUsersRoute: typeof CustomersCodeCspUsersRoute
  CustomersCodeCspIndexRoute: typeof CustomersCodeCspIndexRoute
}

const CustomersCodeCspRouteChildren: CustomersCodeCspRouteChildren = {
  CustomersCodeCspGlobalAdminsRoute: CustomersCodeCspGlobalAdminsRoute,
  CustomersCodeCspLicensesRoute: CustomersCodeCspLicensesRoute,
  CustomersCodeCspMfaRoute: CustomersCodeCspMfaRoute,
  CustomersCodeCspSecureScoreRoute: CustomersCodeCspSecureScoreRoute,
  CustomersCodeCspUsersRoute: CustomersCodeCspUsersRoute,
  CustomersCodeCspIndexRoute: CustomersCodeCspIndexRoute,
}

const CustomersCodeCspRouteWithChildren =
  CustomersCodeCspRoute._addFileChildren(CustomersCodeCspRouteChildren)

interface CustomersCodeEppRouteChildren {
  CustomersCodeEppEndpointsRoute: typeof CustomersCodeEppEndpointsRoute
  CustomersCodeEppIncidentsRoute: typeof CustomersCodeEppIncidentsRoute
  CustomersCodeEppModulesRoute: typeof CustomersCodeEppModulesRoute
  CustomersCodeEppQuarantineRoute: typeof CustomersCodeEppQuarantineRoute
  CustomersCodeEppSlaRoute: typeof CustomersCodeEppSlaRoute
  CustomersCodeEppIndexRoute: typeof CustomersCodeEppIndexRoute
}

const CustomersCodeEppRouteChildren: CustomersCodeEppRouteChildren = {
  CustomersCodeEppEndpointsRoute: CustomersCodeEppEndpointsRoute,
  CustomersCodeEppIncidentsRoute: CustomersCodeEppIncidentsRoute,
  CustomersCodeEppModulesRoute: CustomersCodeEppModulesRoute,
  CustomersCodeEppQuarantineRoute: CustomersCodeEppQuarantineRoute,
  CustomersCodeEppSlaRoute: CustomersCodeEppSlaRoute,
  CustomersCodeEppIndexRoute: CustomersCodeEppIndexRoute,
}

const CustomersCodeEppRouteWithChildren =
  CustomersCodeEppRoute._addFileChildren(CustomersCodeEppRouteChildren)

interface CustomersCodeRmmRouteChildren {
  CustomersCodeRmmAlertsRoute: typeof CustomersCodeRmmAlertsRoute
  CustomersCodeRmmDevicesRoute: typeof CustomersCodeRmmDevicesRoute
  CustomersCodeRmmEventsRoute: typeof CustomersCodeRmmEventsRoute
  CustomersCodeRmmIopsRoute: typeof CustomersCodeRmmIopsRoute
  CustomersCodeRmmMappingRoute: typeof CustomersCodeRmmMappingRoute
  CustomersCodeRmmOverviewRoute: typeof CustomersCodeRmmOverviewRoute
  CustomersCodeRmmPatchRoute: typeof CustomersCodeRmmPatchRoute
  CustomersCodeRmmSlaRoute: typeof CustomersCodeRmmSlaRoute
  CustomersCodeRmmWorkstationsRoute: typeof CustomersCodeRmmWorkstationsRoute
  CustomersCodeRmmIndexRoute: typeof CustomersCodeRmmIndexRoute
}

const CustomersCodeRmmRouteChildren: CustomersCodeRmmRouteChildren = {
  CustomersCodeRmmAlertsRoute: CustomersCodeRmmAlertsRoute,
  CustomersCodeRmmDevicesRoute: CustomersCodeRmmDevicesRoute,
  CustomersCodeRmmEventsRoute: CustomersCodeRmmEventsRoute,
  CustomersCodeRmmIopsRoute: CustomersCodeRmmIopsRoute,
  CustomersCodeRmmMappingRoute: CustomersCodeRmmMappingRoute,
  CustomersCodeRmmOverviewRoute: CustomersCodeRmmOverviewRoute,
  CustomersCodeRmmPatchRoute: CustomersCodeRmmPatchRoute,
  CustomersCodeRmmSlaRoute: CustomersCodeRmmSlaRoute,
  CustomersCodeRmmWorkstationsRoute: CustomersCodeRmmWorkstationsRoute,
  CustomersCodeRmmIndexRoute: CustomersCodeRmmIndexRoute,
}

const CustomersCodeRmmRouteWithChildren =
  CustomersCodeRmmRoute._addFileChildren(CustomersCodeRmmRouteChildren)

interface CustomersCodeSysproRouteChildren {
  CustomersCodeSysproDayEndRoute: typeof CustomersCodeSysproDayEndRoute
  CustomersCodeSysproDtrRoute: typeof CustomersCodeSysproDtrRoute
  CustomersCodeSysproHealthRoute: typeof CustomersCodeSysproHealthRoute
  CustomersCodeSysproHotfixesRoute: typeof CustomersCodeSysproHotfixesRoute
  CustomersCodeSysproJobsRoute: typeof CustomersCodeSysproJobsRoute
  CustomersCodeSysproLicenseRoute: typeof CustomersCodeSysproLicenseRoute
  CustomersCodeSysproOperatorsRoute: typeof CustomersCodeSysproOperatorsRoute
  CustomersCodeSysproSecurityRoute: typeof CustomersCodeSysproSecurityRoute
  CustomersCodeSysproSlaRoute: typeof CustomersCodeSysproSlaRoute
  CustomersCodeSysproSqlRoute: typeof CustomersCodeSysproSqlRoute
  CustomersCodeSysproIndexRoute: typeof CustomersCodeSysproIndexRoute
}

const CustomersCodeSysproRouteChildren: CustomersCodeSysproRouteChildren = {
  CustomersCodeSysproDayEndRoute: CustomersCodeSysproDayEndRoute,
  CustomersCodeSysproDtrRoute: CustomersCodeSysproDtrRoute,
  CustomersCodeSysproHealthRoute: CustomersCodeSysproHealthRoute,
  CustomersCodeSysproHotfixesRoute: CustomersCodeSysproHotfixesRoute,
  CustomersCodeSysproJobsRoute: CustomersCodeSysproJobsRoute,
  CustomersCodeSysproLicenseRoute: CustomersCodeSysproLicenseRoute,
  CustomersCodeSysproOperatorsRoute: CustomersCodeSysproOperatorsRoute,
  CustomersCodeSysproSecurityRoute: CustomersCodeSysproSecurityRoute,
  CustomersCodeSysproSlaRoute: CustomersCodeSysproSlaRoute,
  CustomersCodeSysproSqlRoute: CustomersCodeSysproSqlRoute,
  CustomersCodeSysproIndexRoute: CustomersCodeSysproIndexRoute,
}

const CustomersCodeSysproRouteWithChildren =
  CustomersCodeSysproRoute._addFileChildren(CustomersCodeSysproRouteChildren)

interface CustomersCodeTicketsRouteChildren {
  CustomersCodeTicketsClosedRoute: typeof CustomersCodeTicketsClosedRoute
  CustomersCodeTicketsOpenRoute: typeof CustomersCodeTicketsOpenRoute
  CustomersCodeTicketsResolvedRoute: typeof CustomersCodeTicketsResolvedRoute
  CustomersCodeTicketsSlaRoute: typeof CustomersCodeTicketsSlaRoute
  CustomersCodeTicketsIndexRoute: typeof CustomersCodeTicketsIndexRoute
}

const CustomersCodeTicketsRouteChildren: CustomersCodeTicketsRouteChildren = {
  CustomersCodeTicketsClosedRoute: CustomersCodeTicketsClosedRoute,
  CustomersCodeTicketsOpenRoute: CustomersCodeTicketsOpenRoute,
  CustomersCodeTicketsResolvedRoute: CustomersCodeTicketsResolvedRoute,
  CustomersCodeTicketsSlaRoute: CustomersCodeTicketsSlaRoute,
  CustomersCodeTicketsIndexRoute: CustomersCodeTicketsIndexRoute,
}

const CustomersCodeTicketsRouteWithChildren =
  CustomersCodeTicketsRoute._addFileChildren(CustomersCodeTicketsRouteChildren)

interface CustomersCodeRouteChildren {
  CustomersCodeAmsRoute: typeof CustomersCodeAmsRouteWithChildren
  CustomersCodeCoveRoute: typeof CustomersCodeCoveRouteWithChildren
  CustomersCodeCspRoute: typeof CustomersCodeCspRouteWithChildren
  CustomersCodeEppRoute: typeof CustomersCodeEppRouteWithChildren
  CustomersCodeRmmRoute: typeof CustomersCodeRmmRouteWithChildren
  CustomersCodeSysproRoute: typeof CustomersCodeSysproRouteWithChildren
  CustomersCodeTicketsRoute: typeof CustomersCodeTicketsRouteWithChildren
  CustomersCodeIndexRoute: typeof CustomersCodeIndexRoute
}

const CustomersCodeRouteChildren: CustomersCodeRouteChildren = {
  CustomersCodeAmsRoute: CustomersCodeAmsRouteWithChildren,
  CustomersCodeCoveRoute: CustomersCodeCoveRouteWithChildren,
  CustomersCodeCspRoute: CustomersCodeCspRouteWithChildren,
  CustomersCodeEppRoute: CustomersCodeEppRouteWithChildren,
  CustomersCodeRmmRoute: CustomersCodeRmmRouteWithChildren,
  CustomersCodeSysproRoute: CustomersCodeSysproRouteWithChildren,
  CustomersCodeTicketsRoute: CustomersCodeTicketsRouteWithChildren,
  CustomersCodeIndexRoute: CustomersCodeIndexRoute,
}

const CustomersCodeRouteWithChildren = CustomersCodeRoute._addFileChildren(
  CustomersCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetPackRoute: GetPackRoute,
  LoginRoute: LoginRoute,
  PackRoute: PackRoute,
  ReportsRoute: ReportsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TwoFactorRoute: TwoFactorRoute,
  UiLabRoute: UiLabRoute,
  ApiBootstrapAdminRoute: ApiBootstrapAdminRoute,
  ApiIopsRoute: ApiIopsRoute,
  ApiPatchesRoute: ApiPatchesRoute,
  ApiPortfolioRefreshRoute: ApiPortfolioRefreshRoute,
  ApiReportPreviewRoute: ApiReportPreviewRoute,
  CustomersCodeRoute: CustomersCodeRouteWithChildren,
  DownloadsSplatRoute: DownloadsSplatRoute,
  ApiAgentPackCodeRoute: ApiAgentPackCodeRoute,
  ApiAgentHeartbeatRoute: ApiAgentHeartbeatRoute,
  ApiAgentOnboardRoute: ApiAgentOnboardRoute,
  ApiAgentPackRoute: ApiAgentPackRoute,
  ApiAgentSyncRoute: ApiAgentSyncRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronWeeklyReportRoute: ApiCronWeeklyReportRoute,
  ApiPulsewayWebhookRoute: ApiPulsewayWebhookRoute,
  ApiWpEstateRoute: ApiWpEstateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
