# Write-Csp-Config.ps1
# Interactive: creates C:\RPM-Assure\Sql\csp\Csp.Config.ps1 with Graph + SQL settings.
# Secrets stay only in that file (not in the collect script).
# Pure ASCII. Run on app server.

param(
  [string]$OutPath = "C:\RPM-Assure\Sql\csp\Csp.Config.ps1"
)

$ErrorActionPreference = "Stop"

Write-Host "=== Create Microsoft 365 Graph config ===" -ForegroundColor Cyan
Write-Host "Entra admin center: App registrations -> New registration"
Write-Host "  Type: single tenant"
Write-Host "  API permissions (Application) + Grant admin consent:"
Write-Host "    Organization.Read.All"
Write-Host "    User.Read.All"
Write-Host "    Directory.Read.All"
Write-Host "  Certificates & secrets -> New client secret"
Write-Host ""

function Read-Required([string]$label, [string]$default = "") {
  if ($default) {
    $v = Read-Host "$label [$default]"
    if ([string]::IsNullOrWhiteSpace($v)) { return $default }
    return $v.Trim()
  }
  while ($true) {
    $v = Read-Host $label
    if (-not [string]::IsNullOrWhiteSpace($v)) { return $v.Trim() }
    Write-Host "  required" -ForegroundColor Yellow
  }
}

$tenant  = Read-Required "Directory (tenant) ID"
$client  = Read-Required "Application (client) ID"
$secret  = Read-Required "Client secret VALUE"
$code    = Read-Required "RPM Assure CustomerCode" "RPMINT"
$domain  = Read-Required "Primary domain" "rpmresources.co.za"
$sql     = Read-Required "SQL Server" ".\RPMREPORTS"
$db      = Read-Required "Database" "RPMAssure_App"
$useWin  = Read-Required "Windows SQL auth? (Y/n)" "Y"
$winAuth = ($useWin -notmatch '^[nN]')

$dir = Split-Path -Parent $OutPath
if (-not (Test-Path -LiteralPath $dir)) {
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

$secretEsc = $secret.Replace("'", "''")
$lines = @(
  '# Auto-generated by Write-Csp-Config.ps1 - keep private',
  ('$CspTenantId     = ''{0}''' -f $tenant),
  ('$CspClientId     = ''{0}''' -f $client),
  ('$CspClientSecret = ''{0}''' -f $secretEsc),
  ('$CustomerCode    = ''{0}''' -f $code),
  ('$PrimaryDomain   = ''{0}''' -f $domain),
  ('$SqlServer       = ''{0}''' -f $sql),
  ('$SqlDatabase     = ''{0}''' -f $db),
  ('$WindowsAuth     = ${0}' -f ($(if ($winAuth) { '$true' } else { '$false' })))
)
if (-not $winAuth) {
  $su = Read-Required "SQL user" "Rpm_collect"
  $sp = Read-Required "SQL password"
  $lines += ('$SqlUser         = ''{0}''' -f $su)
  $lines += ('$SqlPassword     = ''{0}''' -f $sp.Replace("'", "''"))
}

[IO.File]::WriteAllLines($OutPath, $lines, [Text.UTF8Encoding]::new($false))
try {
  icacls $OutPath /inheritance:r /grant:r "${env:USERNAME}:(R,W)" "Administrators:(F)" "SYSTEM:(F)" | Out-Null
} catch {}

Write-Host ""
Write-Host "Wrote $OutPath" -ForegroundColor Green
Write-Host "Test Graph token + load:"
Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File C:\RPM-Assure\Sql\csp\Collect-Csp-Graph-To-RPMAssure.ps1 -WindowsAuth"
Write-Host ""
Write-Host "Optional daily schedule:"
Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File C:\RPM-Assure\Sql\csp\Install-Csp-Schedule.ps1"
